#ifndef ICOLORCONFIG_H
#define ICOLORCONFIG_H

#include <QColor>
#include <QStringList>
#include "isingleton.h"

class IColorConfig : public Singleton<IColorConfig>
{
public:
   IColorConfig(token);
   ~IColorConfig();
   IColorConfig(const IColorConfig&) = delete;
   IColorConfig& operator =(const IColorConfig&) = delete;

   QString LoadColorFromID(int colorID);

private:
    void InitColorList();

private:
    QStringList m_colorList;
};

QString LoadColorFromID(int colorID);

/**
 * @brief getHexFromQColor QColor转16进制颜色值
 * @param color QColor变量
 * @return 16进制颜色值，比如#ff12ff00
 */
QString getHexFromQColor(const QColor &color);

enum {
    COLOR_GLOBAL_TEXT_BLACK = 0,
    COLOR_GLOBAL_TEXT_WHITE,

    COLOR_BORDER_NORMAL,
    COLOR_BORDER_HOVER,
    COLOR_EDIT_BACKGROUND,

    COLOR_ICONBTN_TEXT_NORMAL,
    COLOR_ICONBTN_TEXT_DISABLE,
    COLOR_ICONBTN_BACKGROUND_NORMAL,
    COLOR_ICONBTN_BACKGROUND_HOVER,
    COLOR_ICONBTN_BACKGROUND_DISABLE,

    COLOR_TOOLBTN_TEXT_NORMAL,
    COLOR_TOOLBTN_TEXT_DISABLE,
    COLOR_TOOLBTN_BACKGROUND_NORMAL,
    COLOR_TOOLBTN_BACKGROUND_HOVER,
    COLOR_TOOLBTN_BACKGROUND_DISABLE,

    COLOR_COMBOBOXITEM_SELECTION,
    COLOR_COMBOBOXITEM_SELECTION_BACKGROUND,

    COLOR_HOMEBTN_BG_NORMAL,
    COLOR_HOMEBTN_BG_HOVER,
    COLOR_HOMEBTN_BG_PRESSED,
    COLOR_HOMEBTN_BG_CHECKED,
    COLOR_HOMEBTN_TEXT_NORMAL,
    COLOR_HOMEBTN_TEXT_HOVER,
    COLOR_HOMEBTN_TEXT_PRESSED,
    COLOR_HOMEBTN_TEXT_CHECKED,

	COLOR_HOMETOOLBTN_TEXT_TITLE,
    COLOR_HOMETOOLBTN_TEXT_TIPS,
    COLOR_HOMETOOLBTN_HOVER,
    COLOR_HOMEPAGE_BOTTOM_BG,

	COLOR_CALENDAR_WEEKLAB_TEXT,
    COLOR_CALENDAR_TOOLBTN_TEXT,
    COLOR_CALENDAR_TOOLBTN_BG_NORMAL,
    COLOR_CALENDAR_TOOLBTN_BG_HOVER,
    COLOR_CALENDAR_TOOLBTN_BG_DISABLE,
    COLOR_CALENDAR_CALBTN_RECORD,
    COLOR_CALENDAR_CALBTN_TEXT_WORKDAY,
    COLOR_CALENDAR_CALBTN_TEXT_WEEKEND,
    COLOR_CALENDAR_CALBTN_TEXT_SELECT,
	COLOR_TITLE_TEXT,
    COLOR_CALENDAR_CALBTN_TEXT_PREV_OR_NEXT,
    COLOR_CALENDAR_CALBTN_BG_HOVER,
    COLOR_CALENDAR_CALBTN_BG_SELECT,
    COLOR_CALENDAR_CALBTN_BORDER,
    COLOR_CALENDAR_CALBTN_TEXT_DISABLE,
    COLOR_CALENDAR_CALBTN_TEXT_CURRENT_DISABLE,

    COLOR_ACTION_TEXT,
    COLOR_ACTION_BG_NORMAL,
    COLOR_ACTION_BG_HOVER,
    COLOR_RSWINBASE_BORDER,
    COLOR_RSWINBASE_BG,
    COLOR_TRIANGLE_BG,
	COLOR_DIALOG_TITLTBAR_TEXT,
    COLOR_DIALOG_TITLEBAR_BG,
    COLOR_DIALOG_MAINWIDGET_BG,
    COLOR_CPU_NORMAL,
    COLOR_CPU_OCCUPY,
    COLOR_LOCK_BG,
    COLOR_LOCK_TEXT,

    COLOR_TABLEVIEW_BG,
    COLOR_TABLEVIEW_ALTERNATE_BG,
    COLOR_TABLEVIEW_SELECTION_BG,
    COLOR_TABLEVIEW_HEADER_TEXT,
    COLOR_TABLEVIEW_HEADER_BG,
    COLOR_TABLEVIEW_HEADER_BORDER,
    COLOR_TREEVIEW_BG,
    COLOR_TREEVIEW_TEXT,
    COLOR_TREEVIEW_ITEM_BG_HOVER_AND_SELECTION,

    COLOR_QSCROLLBAR_BG,
    COLOR_QSCROLLBAR_HANDLE_NORMAL,
    COLOR_QSCROLLBAR_HANDLE_PRESS,

    COLOR_BASECHECKBOX_TEXT,
    COLOR_COMBOBOX_RECORD_ALL,
    COLOR_COMBOBOX_RECORD_NORMAL,
    COLOR_COMBOBOX_RECORD_ALARM,
    COLOR_COMBOBOX_RECORD_INTELLIGENT,

    COLOR_BASERADIOBTN_TEXT,
    COLOR_SLIDER_GROOVE_BORDER,
    COLOR_SLIDER_MINSIDE,
    COLOR_SLIDER_MAXSIDE,
    COLOR_SWITCHBTN_ON,
    COLOR_SWITCHBTN_ON_DISABLE,
    COLOR_SWITCHBTN_OFF,
    COLOR_SWITCHBTN_OFF_DISABLE,
    COLOR_SWITCHBTN_DOT,

    COLOR_SPINBOX_BG,
    COLOR_SPINBOX_BORDER,
    COLOR_DATETIMEEDIT_BG,
    COLOR_DATETIMEEDIT_BORDER,
    COLOR_DATETIMEEDIT_RS_DROPDOWN_BORDER,
    COLOR_DATETIMEEDIT_RS_POPUP_BG,

    COLOR_LISTWIDGET_BG,
    COLOR_LISTWIDGET_TEXT,
    COLOR_LISTWIDGET_ITEM_BG_HOVER_AND_SELECTION,
    COLOR_LISTWIDGET_ITEM_TEXT_HOVER_AND_SELECTION,

    COLOR_VIDEOSCREENLAYOUTMENU_TOOLBTN_BG_NORMAL,
    COLOR_VIDEOSCREENLAYOUTMENU_TOOLBTN_BG_HOVER,
    COLOR_VIDEOSCREENLAYOUTMENU_TOOLBTN_TEXT_NORMAL,
    COLOR_VIDEOSCREENLAYOUTMENU_TOOLBTN_TEXT_HOVER,

    COLOR_GROUPBOX_BORDER,

    COLOR_WAITING_DIALOG_BG1,
    COLOR_WAITING_DIALOG_BG2,

    COLOR_MSG_POPUP_BG,
    COLOR_MSG_POPUP_TEXT,
    COLOR_MSG_POPUP_TEXT_FAILED,
    COLOR_MSG_POPUP_TITLE_BG,
    COLOR_MSG_POPUP_TITLE_BG_FAILED,
    COLOR_MSG_POPUP_TITLE_TEXT
};

#endif // ICOLORCONFIG_H
