#ifndef RESOURCE_H
#define RESOURCE_H

#if defined(__GNUC__)
#define ATTRIBUTE_UNUSED __attribute__((__unused__))
#else
#define ATTRIBUTE_UNUSED
#endif

#define DIALOG_TITLEBAR_HEIGHT      29


//Alarm
#define ICON_ALARM_SOUNDON                "Alarm/AlarmSoundOn"
#define ICON_ALARM_SOUNDOFF               "Alarm/AlarmSoundOff"
#define ICON_ALARM_OPEN                   "Alarm/AlarmOpen"
#define ICON_ALARM_CLOSE                  "Alarm/AlarmClose"
#define ICON_ALARM_MAXIUM                 "Alarm/AlarmMaxium"
#define ICON_ALARM_AUTOHIDE               "Alarm/AutoHide"
#define ICON_ALARM_AUTOHIDEDISABLE        "Alarm/AutoHideDisable"
#define ICON_ALARM_DELETEALL              "Alarm/AlarmDeleteAll"
#define ICON_ALARM_POPUPOFF               "Alarm/AlarmPopupOff"
#define ICON_ALARM_POPUPON                "Alarm/AlarmPopupOn"
#define ICON_ALARM_NOPICTURE              "Alarm/NoPicture"
#define ICON_ALARM_NORECORD               "Alarm/NoRecord"
#define ICON_ALARM_NOVIDEO                "Alarm/NoVideo"
#define ICON_ALARM_PROCESS                "Alarm/Process"
#define ICON_ALARM_PROCESSED              "Alarm/Processed"
#define ICON_ALARM_SENDEMAIL              "Alarm/SendEmail"
#define ICON_ALARM_UNPROCESS              "Alarm/UnProcess"
#define ICON_ALARM_LOCALON                "Alarm/AlarmLocalOn"
#define ICON_ALARM_LOCALOFF               "Alarm/AlarmLocalOff"
#define ICON_ALARM_REMOTEON               "Alarm/AlarmRemoteOn"
#define ICON_ALARM_REMOTEOFF              "Alarm/AlarmRemoteOff"

//common
//comm dialog_titlebar
#define PNG_COMMON_DIALOG_CLOSE             "common/CustomDialog/dialog-closebutton"
#define PNG_COMMON_DIALOG_INFO              "common/CustomDialog/info"
#define PNG_COMMON_DIALOG_INFO_PLAYER       "common/CustomDialog/info_player"
#define PNG_COMMON_DIALOG_ALARM             "common/CustomDialog/urgentAlarm"
//comm dialog widget
#define PNG_COMMON_SUCCESS                  "common/CustomDialog/success"
#define PNG_COMMON_FAILED                   "common/CustomDialog/failed"

#define ICON_COMMON_LOADGIF                 "common/CustomDialog/loading"
#define ICON_COMMON_DEV_EDITE               "common/CustomDialog/devInfo-edit"
#define ICON_COMM_CLOSE                     "common/close"
#define ICON_COMM_DEFAULTPIC                "common/defaultPic"

#define PNG_COMMON_TABCLOSE				    "common/tab_close"
#define PNG_COMM_SWITCH_ON                  "common/switch_on"
#define PNG_COMM_SWITCH_OFF                 "common/switch_off"
#define PNG_COMM_SWITCH_ON_DISABLED         "common/switch_on_disabled"
#define PNG_COMM_SWITCH_OFF_DISABLED        "common/switch_off_disabled"
#define ICON_COMM_MENUBUTTON                "common/menubutton"
#define ICON_COMM_MENUSELECTED              "common/MenuSelected"
#define PNG_COMMON_MAINTABCLOSE	            "common/closebutton"
#define ICON_COMMON_MAX                     "common/maxbutton"
#define ICON_COMMON_MIN                     "common/minbutton"
#define ICON_COMMON_USER                    "common/userSwitch"
#define ICON_COMMON_ABOUT                   "common/about"
#define ICON_COMMON_USERSWITCH              "common/userSwitch"
#define ICON_COMMON_VIEW                    "common/view"
#define ICON_COMMON_ARROWL                  "common/arrow-left"
#define ICON_COMMON_ARROWL_W                "common/arrow-left-w"
#define ICON_COMMON_ARROWR                  "common/arrow-right"
#define ICON_COMMON_ARROWR_W                "common/arrow-right_w"
#define ICON_COMMON_1W                      "common/1-w"
#define ICON_COMMON_1B                      "common/1-b"
#define ICON_COMMON_2W                      "common/2-w"
#define ICON_COMMON_2B                      "common/2-b"
#define ICON_COMMON_3W                      "common/3-w"
#define ICON_COMMON_3B                      "common/3-b"
#define ICON_COMMON_4W                      "common/4-w"
#define ICON_COMMON_4B                      "common/4-b"
#define ICON_COMMON_5W                      "common/5-w"
#define ICON_COMMON_5B                      "common/5-b"
#define ICON_COMMON_6W                      "common/6-w"
#define ICON_COMMON_6B                      "common/6-b"
#define ICON_COMMON_7W                      "common/7-w"
#define ICON_COMMON_7B                      "common/7-b"
#define ICON_COMMON_8W                      "common/8-w"
#define ICON_COMMON_8B                      "common/8-b"
#define ICON_COMMON_9B                      "common/9-b"
#define ICON_COMMON_10B                     "common/10-b"
#define ICON_COMMON_MINUS16                 "common/minus16"
#define ICON_COMMON_MODIFY                  "common/modify"
#define ICON_COMMON_TAB_MORE_NORMAL         "common/tab_more_normal"
#define ICON_COMMON_TAB_MORE_SELECT         "common/tab_more_selected"
#define ICON_COMMON_TAB_MORE_PLAY           "common/tab_more_play"
#define ICON_COMMON_EXPAND                  "common/expand"
#define ICON_COMMON_CLOSE                   "common/close"
#define ICON_COMMON_DOWNARROW               "common/DownArrow"
#define ICON_COMMON_UPARROW                 "common/UpArrow"
#define ICON_COMMON_RIGHTARROW              "common/RightArrow"
#define ICON_COMMON_LEFTARROW               "common/LeftArrow"
#define ICON_COMMON_ELLIPSES                "common/Ellipses"
#define ICON_COMM_LOADING                   "common/Loading"
#define ICON_COMM_NORMAL                    "common/normal"
#define ICON_COMM_ALLOW                     "common/Allow"
#define ICON_COMM_DENY                      "common/Deny"
#define ICON_COMM_STRANGER                  "common/Stranger"
#define ICON_COMM_VIDEO_CLOSE               "common/video_close"
#define ICON_PREVIEW_360ERROR               "preview/360_error"
#define PNG_COMMON_DROP_DOWN                "common/datetime-drop-down"
#define ICON_COMMON_FILEOPEN                "common/folder_open"

//Equipmentmanagement
#define PNG_EQUIPMENTMANAGEMENT_OFFLINE                 "Equipmentmanagement/Offline"
#define PNG_EQUIPMENTMANAGEMENT_ONLINE                  "Equipmentmanagement/Online"
#define PNG_EQUIPMENTMANAGEMENT_FIRSTLOGIN              "Equipmentmanagement/FirstLogin"
#define PNG_EQUIPMENTMANAGEMENT_BLOCK                   "Equipmentmanagement/Block"
#define PNG_EQUIPMENTMANAGEMENT_EDIT                    "Equipmentmanagement/Edit"
#define PNG_EQUIPMENTMANAGEMENT_DELETE                  "Equipmentmanagement/delete"
#define PNG_EQUIPMENTMANAGEMENT_SETTING                 "Equipmentmanagement/Setting"
#define PNG_EQUIPMENTMANAGEMENT_RECORDEMPTY             "Equipmentmanagement/RecordEmpty"
#define PNG_EQUIPMENTMANAGEMENT_RECORD                  "Equipmentmanagement/Record"
#define PNG_EQUIPMENTMANAGEMENT_ADD                     "Equipmentmanagement/AddDevice"
#define PNG_EQUIPMENTMANAGEMENT_DELETEDEVICE            "Equipmentmanagement/DeleteDevice"
#define PNG_EQUIPMENTMANAGEMENT_EXPORT                  "Equipmentmanagement/Export"
#define PNG_EQUIPMENTMANAGEMENT_IMPORT                  "Equipmentmanagement/Import"
#define PNG_EQUIPMENTMANAGEMENT_ADDWHITE                "Equipmentmanagement/AddDevice_white"
#define PNG_EQUIPMENTMANAGEMENT_DELETEDEV_WHITE         "Equipmentmanagement/DeleteDevice_white"
#define PNG_EQUIPMENTMANAGEMENT_INITIALIZE              "Equipmentmanagement/initialization"
#define PNG_EQUIPMENTMANAGEMENT_KEY                     "Equipmentmanagement/Key"
#define PNG_EQUIPMENTMANAGEMENT_FIRSTLOGINDEV           "Equipmentmanagement/logindev"
#define PNG_EQUIPMENTMANAGEMENT_FIRSTLOGOUTDEV          "Equipmentmanagement/logoutdev"
#define PNG_EQUIPMENTMANAGEMENT_BATCHLOGINDEV           "Equipmentmanagement/batchlogin"
#define PNG_EQUIPMENTMANAGEMENT_BATCHLOGOUTDEV          "Equipmentmanagement/batchlogout"
#define PNG_EQUIPMENTMANAGEMENT_UPDATESUC               "Equipmentmanagement/UpdateSuccess"
#define PNG_EQUIPMENTMANAGEMENT_UADATEFAIL              "Equipmentmanagement/UpdateFail"

#define PNG_EQUIPMENTMANAGEMENT_PARAEXPORT              "Equipmentmanagement/paraExport"
#define PNG_EQUIPMENTMANAGEMENT_PARAIMPORT              "Equipmentmanagement/paraImport"
#define PNG_EQUIPMENTMANAGEMENT_BATCHUPGRADE            "Equipmentmanagement/BatchUpgrade"
#define PNG_EQUIPMENTMANAGEMENT_CLOUDFAIL               "Equipmentmanagement/cloud_fail"
#define PNG_EQUIPMENTMANAGEMENT_CLOUDNOT                "Equipmentmanagement/cloud_not"
#define PNG_EQUIPMENTMANAGEMENT_CLOUDNOSUPPORT          "Equipmentmanagement/cloud_nosupport"
#define PNG_EQUIPMENTMANAGEMENT_CLOUDON                 "Equipmentmanagement/cloud_on"
#define PNG_EQUIPMENTMANAGEMENT_CLOUDWHITE              "Equipmentmanagement/cloud_white"
#define PNG_EQUIPMENTMANAGEMENT_ADDCLOUD                "Equipmentmanagement/addcloud"
#define PNG_EQUIPMENTMANAGEMENT_CLOUDLOADING            "Equipmentmanagement/cloud_loading"
#define PNG_EQUIPMENTMANAGEMENT_CLOUDRECORDED           "Equipmentmanagement/cloud_recorded"
#define PNG_EQUIPMENTMANAGEMENT_QRSMALL                 "Equipmentmanagement/QRsmall"
#define PNG_EQUIPMENTMANAGEMENT_QRSMALL_HOVER           "Equipmentmanagement/QRsmall_hover"
#define PNG_EQUIPMENTMANAGEMENT_SCROLLBAR_DOWN          "Equipmentmanagement/Scrollbar_down"
#define PNG_EQUIPMENTMANAGEMENT_SCROLLBAR_RIGHT         "Equipmentmanagement/Scrollbar_right"
#define PNG_EQUIPMENTMANAGEMENT_BRANCH_MORE             "Equipmentmanagement/branch_more"
#define PNG_EQUIPMENTMANAGEMENT_BRANCH_END              "Equipmentmanagement/branch_end"
#define PNG_EQUIPMENTMANAGEMENT_EDIT_SHARE              "Equipmentmanagement/EditShare"
#define PNG_EQUIPMENTMANAGEMENT_REMOVE_SHARE            "Equipmentmanagement/RemoveShare"
#define ICON_EQUIPMENTMANAGEMENT_EXPANDUNACCEPT         "Equipmentmanagement/expand_unaccept"
#define ICON_EQUIPMENTMANAGEMENT_RETRACTUNACCEPT        "Equipmentmanagement/retract_unaccept"
#define ICON_EQUIPMENTMANAGEMENT_ACCEPTBG               "Equipmentmanagement/acceptbackgroup"
#define ICON_EQUIPMENTMANAGEMENT_CHANNELON              "Equipmentmanagement/ChannelOn"
#define ICON_EQUIPMENTMANAGEMENT_DEVICEON               "Equipmentmanagement/Device"
#define ICON_EQUIPMENTMANAGEMENT_DROPDOWN               "Equipmentmanagement/dropdownbtn"
#define ICON_EQUIPMENTMANAGEMENT_NOREAD                 "Equipmentmanagement/noread"
#define ICON_EQUIPMENTMANAGEMENT_ADDSHARE               "Equipmentmanagement/addshare"
#define ICON_EQUIPMENTMANAGEMENT_SHAREBG                "Equipmentmanagement/sharebackgroud"
#define ICON_EQUIPMENTMANAGEMENT_SHARE                  "Equipmentmanagement/Share"

//file managenment
#define ICON_FILE_VIDEO_PLAYBTN                     "file/video_playBtn"
#define ICON_FILE_VIDEO_COMM_COVER                  "file/video_comm_cover"
#define ICON_FILE_VIDEO_BLACK                       "file/black"


//login
#define ICON_LOGIN_CLOSE                  "login/Close"
#define ICON_LOGIN_DEVICE                 "login/Device"
#define ICON_LOGIN_DOWNINPUT              "login/DownInput"
#define ICON_LOGIN_FINISHED               "login/finished"
#define ICON_LOGIN_INVISIBLE              "login/Invisible"
#define ICON_LOGIN_ONGOING                "login/ongoing"
#define ICON_LOGIN_PASSWORD               "login/Password"
#define ICON_LOGIN_PORT                   "login/Port"
#define ICON_LOGIN_UNFINISHED             "login/unfinished"
#define ICON_LOGIN_USER                   "login/User"
#define ICON_LOGIN_VISIBLE                "login/Visible"
#define ICON_LOGIN_WHITEDOWN              "login/WhiteDownInput"
#define ICON_LOGIN_SUCCESS                "login/Success"
#define ICON_LOGIN_PWDERROR               "login/passworderror"
#define ICON_LOGIN_PWDCORRECT             "login/passwordcorrect"
#define ICON_LOGIN_NOTICE                 "login/Notice"

//playback
#define ICON_PLAYBACK_LASTMONTH           "playback/lastMonth"
#define ICON_PLAYBACK_LASTYEAR            "playback/lastYear"
#define ICON_PLAYBACK_NEXTMONTH           "playback/nextMonth"
#define ICON_PLAYBACK_NEXTYEAR            "playback/nextYear"
#define ICON_PLAYBACK_LAYOUTMENU          "playback/layoutMenu"
#define ICON_PLAYBACK_CUT                 "playback/Cut"
#define ICON_PLAYBACK_FULLSCREENT         "playback/Full"
#define ICON_PLAYBACK_DOWN                "playback/down"
#define ICON_PLAYBACK_DOWNLOAD            "playback/Download"
#define ICON_PLAYBACK_FILTERBTN           "playback/FilterBtn"
#define ICON_PLAYBACK_SEARCHBTN           "playback/SearchBtn"
#define ICON_PLAYBACK_SEARCHINPUT         "playback/SearchInput"
#define ICON_PLAYBACK_PLAY                "playback/Play"
#define ICON_PLAYBACK_SYN                 "playback/video-synchronization"
#define ICON_PLAYBACK_SYN_NEW             "playback/video-synchronization_new"
#define ICON_PLAYBACK_ASYN_NEW            "playback/video-asynchronization_new"
#define ICON_PLAYBACK_BACKUP              "playback/Backup"
#define ICON_PLAYBACK_UNLOCK              "playback/Unlock"
#define ICON_PLAYBACK_LOCK                "playback/Lock"

#define ICON_PLAYBACK_ALLLOCK             "playback/Alllock"
#define ICON_PLAYBACK_ALLUNLOCK           "playback/Allunlock"
#define ICON_PLAYBACK_SAVEFILE            "playback/savefile"
#define ICON_PLAYBACK_DELETEFILE          "playback/deletefile"

#define ICON_PLAYBACK_MUTE                "playback/Mute"
#define ICON_PLAYBACK_PAUSE               "playback/Pause"
#define ICON_PLAYBACK_RIGHT               "playback/right"
#define ICON_PLAYBACK_LEFT                "playback/left"
#define ICON_PLAYBACK_STOP                "playback/Stop"
#define ICON_PLAYBACK_VOLUME              "playback/Volume"
#define ICON_PLAYBACK_SINGLE              "playback/Single"
#define ICON_PLAYBACK_RIGHTTIMELINE       "playback/RightTimeline"
#define ICON_PLAYBACK_LEFTTIMELINE        "playback/LeftTimeline"
#define ICON_PLAYBACK_ZoomADD             "playback/Zoom+Timeline"
#define ICON_PLAYBACK_ZoomREDUCE          "playback/Zoom-Timeline"
#define ICON_PLAYBACK_BACKEWARD           "playback/Backward"
#define ICON_PLAYBACK_DRAG                "playback/drag-video"
#define ICON_PLAYBACK_POINTER             "playback/Pointer"
#define ICON_PLAYBACK_FORWARA             "playback/Forward"
#define ICON_PLAYBACK_CAPTURE             "playback/Snap"
#define ICON_PLAYBACK_ZOOM                "playback/Zoom"
#define ICON_PLAYBACK_RECORD              "playback/Record"
#define ICON_PLAYBACK_RECORDING           "playback/Recording"
#define ICON_PLAYBACK_SLOWER              "playback/slower"
#define ICON_PLAYBACK_STEP                "playback/SingleShow"

#define ICON_PLAYBACK_SLOWER_2            "playback/slower_2"
#define ICON_PLAYBACK_SLOWER_4            "playback/slower_4"
#define ICON_PLAYBACK_SLOWER_8            "playback/slower_8"
#define ICON_PLAYBACK_SLOWER_16           "playback/slower_16"
#define ICON_PLAYBACK_FASTER_2            "playback/faster_2"
#define ICON_PLAYBACK_FASTER_4            "playback/faster_4"
#define ICON_PLAYBACK_FASTER_8            "playback/faster_8"
#define ICON_PLAYBACK_FASTER_16           "playback/faster_16"
#define ICON_PLAYBACK_FASTER_NOR          "playback/faster_nor"

#define ICON_PLAYBACK_VIDEO_PLAY          "playback/Controlbar_play"
#define ICON_PLAYBACK_VIDEO_STOP          "playback/Controlbar_stop"
#define ICON_PLAYBACK_VIDEO_PAUSE         "playback/Controlbar_pause"
#define ICON_PLAYBACK_VIDEO_SINGLE        "playback/Controlbar_single"
#define ICON_PLAYBACK_VIDEO_FORWARA       "playback/Controlbar_forward"
#define ICON_PLAYBACK_VIDEO_BACKWARD      "playback/Controlbar_Backward"
#define ICON_PLAYBACK_VIDEO_RECORD        "playback/Controlbar_record"
#define ICON_PLAYBACK_VIDEO_TALKBACK      "playback/Controlbar_talkback"
#define ICON_PLAYBACK_VIDEO_MUTE          "playback/Controlbar_mute"
#define ICON_PLAYBACK_VIDEO_VOLUME        "playback/Controlbar_volume"
#define ICON_PLAYBACK_VIDEO_RECORDING     "playback/Controlbar_recording"
#define ICON_PLAYBACK_CONTROLBAR_FULLSCREEN    "playback/Controlbar_fullScreen"
#define ICON_PLAYBACK_VIDEO_BACK          "playback/Controlbar_back"

#define ICON_PLAYBACK_PRE_30S             "playback/Pre30s"
#define ICON_PLAYBACK_POST_30S            "playback/Post30s"

#define ICON_PLAYBACK_PLAYBACK            "playback/playback"
#define ICON_PLAYBACK_PLAYBACK_BLUE       "playback/playback_blue"

#define ICON_PLAYBACK_RADIO_UNSELECTED                  "playback/Radio_unselected"
#define ICON_PLAYBACK_RADIO_SELECTED                    "playback/Radio_selected"
#define ICON_PLAYBACK_TIMEUP                            "playback/TimeUp"
#define ICON_PLAYBACK_TIMEDOWN                          "playback/TimeDown"
#define ICON_PLAYBACK_CHECKBOX_UNSELECTED               "playback/Checkbox_unselected"
#define ICON_PLAYBACK_CHECKBOX_SELECTED                 "playback/Checkbox_selected"
#define ICON_PLAYBACK_CHECKBOX_PARTSELECTED             "playback/Checkbox_partialselected"
#define ICON_PLAYBACK_CHECKBOX_SELECTED_DISABLED        "playback/Checkbox_selected_disabled"
#define ICON_PLAYBACK_CHECKBOX_UNSELECTED_DISABLED      "playback/Checkbox_unselected_disabled"
#define ICON_PLAYBACK_CHECKBOX_PARTSELECTED_DISABLED    "playback/Checkbox_partialselected_disabled"
#define ICON_PLAYBACK_SHOT_SCREEN                       "playback/ShotScreen"

#define ICON_PLAYBACK_DEFAULTADDTAG             "playback/DefaultAddTag"
#define ICON_PLAYBACK_CUSTOMADDTAG              "playback/CustomAddTag"
#define ICON_PLAYBACK_TAGPLAY                   "playback/TagPlay"
#define ICON_PLAYBACK_TAGVIDEO                  "playback/tagvideo"
#define ICON_PLAYBACK_TAGVIDEO_ON               "playback/tagvideo_on"
#define ICON_PLAYBACK_PLAYSMART                 "playback/playsmart"
#define ICON_PLAYBACK_OPENFILE                  "playback/openfile"
#define ICON_PLAYBACK_PLAYERITEM                "playback/playeritem"
#define ICON_PLAYBACK_PLAYERLOCKITEM            "playback/playerlockitem"
#define ICON_PLAYBACK_CLEARSMART                "playback/ClearSmart"
#define ICON_PLAYBACK_SMARTSEARCH               "playback/SmartReSearch"
#define ICON_PLAYBACK_PBLOCAL                   "playback/PB_local"
#define ICON_PLAYBACK_PBREMOTE                  "playback/PB_remote"
#define ICON_PLAYBACK_PBLOCAL_ON                "playback/PB_localOn"
#define ICON_PLAYBACK_PBREMOTE_ON               "playback/PB_remoteOn"
#define ICON_PLAYBACK_DELUNCOMPLETE             "playback/ClearUnComplete"
#define ICON_PLAYBACK_DELCOMPLETE               "playback/ClearComplete"
#define ICON_PLAYBACK_LISTVIEW                  "playback/Listview"
#define ICON_PLAYBACK_THUMBNAIL                 "playback/Thumbnail"
#define ICON_PLAYBACK_FISHEYE                   "playback/fisheye"

//preview
#define ICON_HIDE                         "preview/hide"
#define ICON_SHOW                         "preview/show"
#define ICON_PREVIEW_FULLSCREEN           "preview/action_fullscreen"
#define ICON_PREVIEW_STOP                 "preview/stop"
#define ICON_PREVIEW_PLAY                 "preview/play"
#define ICON_AUTO_SWITCH_SCREEN           "preview/auto-switch-screen"
#define ICON_PREVIEW_EXIT                 "preview/action_stop"
#define ICON_PREVIEW_PTZ                  "preview/action_PTZ"
#define ICON_PREVIEW_BACK                 "preview/action_back"
#define ICON_PREVIEW_FORWARD              "preview/action_forward"
#define ICON_PREVIEW_FISHEYE              "preview/action_fisheye"
#define ICON_PREVIEW_NEXT                 "preview/action_nextpage"
#define ICON_PREVIEW_PREV                 "preview/action_previouspage"
#define ICON_PREVIEW_REC                  "preview/action_record"
#define ICON_PREVIEW_REC_R                "preview/action_record_rec"
#define ICON_PREVIEW_SNAP                 "preview/action_snap"
#define ICON_PREVIEW_TALK                 "preview/action_talk"
#define ICON_PREVIEW_TALK_ON              "preview/action_talk_on"
#define ICON_PREVIEW_SD_OFF               "preview/action_sd"
#define ICON_PREVIEW_HD_OFF               "preview/action_hd"
#define ICON_PREVIEW_STREAM_SET           "preview/action_streamSet"
#define ICON_PREVIEW_MODIFY_PWD           "preview/action_modifypwd"
#define ICON_PREVIEW_ACTION_IPSPEAKER_TALK       "preview/action_ipspeaker_talk"
#define ICON_PREVIEW_ACTION_IPSPEAKER_TALK_ON    "preview/action_ipspeaker_talk_on"
#define ICON_PREVIEW_IPSPEAKER_INTERCOM          "preview/action_ipspeaker_intercom"
#define ICON_PREVIEW_IPSPEAKER_INTERCOM_ON       "preview/action_ipspeaker_intercom_on"
#define ICON_PREVIEW_IPSPEAKER_VOICEBORADCAST    "preview/action_ipspeaker_voicebroadcast"
#define ICON_PREVIEW_IPSPEAKER_VOICEBORADCAST_ON "preview/action_ipspeaker_voicebroadcast_on"
#define ICON_PREVIEW_IPSPEAKER_TALK       "preview/ipspeaker_talk"
#define ICON_PREVIEW_IPSPEAKER_BROADCAST  "preview/ipspeaker_broadcast"
#define ICON_PREVIEW_PRESETPOINT          "preview/Add"
#define ICON_PREVIEW_CHANNELICON          "preview/ChannelTree"
#define ICON_PREVIEW_PTZDISCICON          "preview/PTZ_disc"
#define ICON_PREVIEW_PTZDISCUTC           "preview/Ptz_discUtc"
#define ICON_PREVIEW_PTZ_MINUS            "preview/Speed-"
#define ICON_PREVIEW_PTZ_PLUS             "preview/Speed+"
#define ICON_PREVIEW_PTZ_HANDLE           "preview/SpeedHandle"
#define ICON_PREVIEW_PTZ_ZOOMIN           "preview/+Btn"
#define ICON_PREVIEW_PTZ_ZOOMOUT          "preview/-Btn"
#define ICON_PREVIEW_PTZ_ZOOM             "preview/Zoom"
#define ICON_PREVIEW_PTZ_FOCUS            "preview/Focus"
#define ICON_PREVIEW_PTZ_IRIS             "preview/Iris"
#define ICON_PREVIEW_PTZ_CRUISEPLAY       "preview/CruisePlay"
#define ICON_PREVIEW_CTRBARCAPTURE        "preview/CtrBar_snap"
#define ICON_PREVIEW_CTRBARRECORD         "preview/CtrBar_record"
#define ICON_PREVIEW_CTRBARTALK           "preview/CtrBar_talk"
#define ICON_PREVIEW_CTRBARIPSPEAKERTALK  "preview/CtrBar_ipspeaker_talk"
#define ICON_PREVIEW_CTRBARZOOM           "preview/CtrBar_zoom"
#define ICON_PREVIEW_CTRBARCOLOR          "preview/CtrBar_color"
#define ICON_PREVIEW_CTRBARFISHEYE        "preview/CtrBar_fisheye"
#define ICON_PREVIEW_CTRBARSTOP           "preview/CtrBar_stop"
#define ICON_PREVIEW_CTRBARFULLSCREEN     "preview/CtrBar_fullscreen"
#define ICON_PREVIEW_CTRBAR3DPOS          "preview/CtrBar_3dpostion"
#define ICON_PREVIEW_COLORSETTING         "preview/action_color"
#define ICON_PREVIEW_ACTION_PLAY          "preview/action_play"
#define ICON_PREVIEW_BRIGHTNESS           "preview/Brightness"
#define ICON_PREVIEW_CHROMA               "preview/Chroma"
#define ICON_PREVIEW_CONTRAST             "preview/contrast"
#define ICON_PREVIEW_SATURATION           "preview/saturation"
#define ICON_PREVIEW_SHARPNESS            "preview/sharpness"
#define ICON_PREVIEW_PALETTE              "preview/palette"
#define ICON_PREVIEW_LOADVIDEO            "preview/Loading"
#define ICON_PREVIEW_CLIP                 "preview/Clip"
#define ICON_PREVIEW_SAVEVIEW             "preview/SaveView"
#define ICON_PREVIEW_FULL                 "preview/Full"
#define ICON_PREVIEW_PLAYALL              "preview/PlayAll"
#define ICON_PREVIEW_BUZZER               "preview/Buzzer"
#define ICON_PREVIEW_STOPALL              "preview/StopAll"
#define ICON_PREVIEW_STOP                 "preview/stop"
#define ICON_PREVIEW_SD                   "preview/SD"
#define ICON_PREVIEW_HD                   "preview/HD"
#define ICON_PREVIEW_SOUND                "preview/sound"
#define ICON_PREVIEW_SOUND_OFF            "preview/sound_off"
#define ICON_PREVIEW_DELETE               "preview/Delete"
#define ICON_PREVIEW_ZOOM_MOUSE_ICON      "preview/zoom_mouse_icon"
#define ICON_PREVIEW_CUT_MOUSE_ICON       "preview/Cut_mouse_icon"
#define ICON_PREVIEW_3DPTZ_MOUSE_ICON     "preview/3dptz_mouse_icon"
#define ICON_PREVIEW_TOURSTOP             "preview/TourStop"
#define ICON_PREVIEW_SOUNDOFF             "preview/soundOff"
#define ICON_PREVIEW_SOUNDON              "preview/soundOn"
#define ICON_PREVIEW_UNMATCHED            "preview/UnmatchFace"
#define ICON_PREVIEW_SHOWFACE             "preview/showFace"
#define ICON_PREVIEW_HIDEFACE             "preview/hideFace"
#define ICON_PREVIEW_DEVTALKON            "preview/DevTalkOn"
#define ICON_PREVIEW_DEVTALKOFF           "preview/DevTalkOff"
#define ICON_PREVIEW_FASTPLAYBACK         "preview/fastplayback"
#define ICON_PREVIEW_CUSTOMEDIT           "preview/CustomEdit"
#define ICON_PREVIEW_CUSTOMLAYOUT         "preview/CustomLayout"
#define ICON_PREVIEW_ALARMICON_ON         "preview/AlarmIcon"
#define ICON_PREVIEW_ALARMICON_OFF        "preview/AlarmIcon_off"
#define ICON_PREVIEW_BUZZER_OFF           "preview/Buzzer_off"
#define ICON_PREVIEW_BUZZER_ON            "preview/Buzzer_on"
#define ICON_PREVIEW_RBLIGHT              "preview/RB_Light"
#define ICON_PREVIEW_MANUALALARMICON      "preview/ManualAlarm"
#define ICON_PREVIEW_SOUND_OFF_DISABLED   "preview/sound_off_disabled"
#define ICON_PREVIEW_CLEAR                "preview/schClear"

#define ICON_MAINVIEW_LAYOUT1             "preview/mainview-layout1"
#define ICON_MAINVIEW_DISLAYOUT1          "preview/playback-layout1_disable"
#define ICON_PLAYBACK_FULLSCREEN          "preview/mainview-fullscreen"
#define ICON_PLAYBACK_DISFULLSCREEN       "preview/playback-fullscreen_disable"
#define ICON_PLAYBACK_EXIT                "preview/playback-exit"
#define ICON_PLAYBACK_DISEXIT             "preview/playback-exit_disable"

#define ICON_PREVIEW_ZOOM_OUT             "preview/zoomout"
#define ICON_PREVIEW_ZOOM_IN              "preview/zoomin"
#define ICON_PREVIEW_IRIS_ADD             "preview/irisadd"
#define ICON_PREVIEW_IRIS_MINUS           "preview/irisminus"
#define ICON_PREVIEW_FOCUS_FAR            "preview/focusfar"
#define ICON_PREVIEW_FOCUS_NEAR           "preview/focusnear"
#define ICON_PREVIEW_3D_POSITION          "preview/3dpostion"
#define ICON_PREVIEW_AUTOFOCUS            "preview/autofocus"
#define ICON_PREVIEW_HUMANTRACE           "preview/humantrace"
#define ICON_PREVIEW_RESET                "preview/reset"
#define ICON_PREVIEW_WATCHMODE            "preview/watchmode"
#define ICON_PREVIEW_PRESET_CALL          "preview/preset_call"
#define ICON_PREVIEW_PRESET_DELETE        "preview/preset_delete"
#define ICON_PREVIEW_PRESET_ADD           "preview/preset_add"
#define ICON_PREVIEW_PTZPLAY              "preview/ptzplay"
#define ICON_PREVIEW_PTZSTOP              "preview/ptzstop"
#define ICON_PREVIEW_PTZDELETE            "preview/ptzdelete"
#define ICON_PREVIEW_PTZSAVE              "preview/ptzsave"
#define ICON_PREVIEW_TRACE_ADD            "preview/trace_add"
#define ICON_PREVIEW_TRACE_DELETE         "preview/trace_delete"
#define ICON_PREVIEW_TRACE_UP             "preview/trace_up"
#define ICON_PREVIEW_TRACE_DOWN           "preview/trace_down"
#define ICON_PREVIEW_AIALARMSHOW          "preview/AiAlarmShow"
#define ICON_PREVIEW_AIALARMHIDE          "preview/AiAlarmHide"
#define ICON_PREVIEW_CTRBARPTZ            "preview/CtrBar_ptz"
#define ICON_PREVIEW_DEVINFO              "preview/dev_info"
#define ICON_PREVIEW_DEVICETALK           "preview/devaction_talk"
#define ICON_PREVIEW_DEVICETALK_ON        "preview/devaction_talk_on"
#define ICON_PREVIEW_DEVCTRBARTALK        "preview/devCtrBar_talk"
#define ICON_PREVIEW_SWITCHSCALE          "preview/SwitchScale"
#define ICON_PREVIEW_TALK_SHOW            "preview/talkShow"
#define ICON_PREVIEW_TALK_STOP            "preview/talkStop"
#define ICON_PREVIEW_IPSPEAKER_SHOW       "preview/ipspeakerShow"
#define ICON_PREVIEW_SYNC_CHANNELNAME     "preview/SyncChannelName"
#define ICON_PREVIEW_TURNPTZ              "preview/turntableptz"
#define ICON_PREVIEW_SETPOS               "preview/SetPosition"
#define ICON_PREVIEW_GOPOS                "preview/GotoPosition"

#define ICON_PREVIEW_HMIRRORBTN           "preview/hmirror_btn"
#define ICON_PREVIEW_VMIRRORBTN           "preview/vmirror_btn"
#define ICON_PREVIEW_PANORAMICBTN         "preview/panoramic_btn"
#define ICON_PREVIEW_COVERBTN             "preview/cover_btn"
#define ICON_PREVIEW_MIRRORMODE           "preview/Mirrormode"

//splash start
#define ICON_FILE_SPLASH_LOADING          "splash/splash_load"


#endif // RESOURCE_H










